fullnameOverride: openfga-db
postgres:
  database: openfga
  username: openfga
  password: openfga
  pgdata: /var/lib/postgresql/data/pgdata
persistence:
  size: 5Gi
  mountPath: /var/lib/postgresql/data
  volumeClaimTemplateName: data
probes:
  readiness:
    execCommand: ["pg_isready", "-U", "openfga", "-d", "openfga"]
  liveness:
    execCommand: ["pg_isready", "-U", "openfga", "-d", "openfga"]
